### PR TITLE
Make plugin work with kong v1

### PR DESCRIPTION
**Pull request by kayano**

### CODE REVIEW

**Comment by kayano** [comment]
Hi @eyolas. Are you still maintaining the plugin?

Thanks,
Tomek

**Comment by eyolas** [comment]
Hi kayano. Yes, i continue to maintain the plugin. I use kong (>v1) in many production env with this plugin. 
Thx for pull request. I test soon and publish the new version (in v2.0.0).

**Comment by kayano** [comment]
with `kong version: 1.4.2-0-enterprise-k8s` and `version 1.1-1 of kong-plugin-referer` I'm getting:
```
[error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:618: ....luarocks/share/lua/5.1/kong/plugins/referer/handler.lua:5: module 'kong.tools.responses' not found:No LuaRocks module found for kong.tools.responses
```

**Comment by kayano** [comment]
@eyolas any chance to have it merged soon?

**Comment by yourapiexpert** [comment]
@eyolas Please could you merge the PR from @kayano in to your extremely useful plugin?  We want to switch to Kong 2.0 but this plugin breaks without the PR.

**Comment by eyolas** [comment]
@yourapiexpert i'll prepare an upgrade this week. The readme did not change in this pull request, so i don't know if the tests passed.

**Comment by eyolas** [comment]
Plugin is updated (see https://luarocks.org/modules/eyolas/kong-plugin-referer/2.0-0)

**Comment by 0x657373656C6C** [comment]
Thank you so very much @eyolas - it is greatly appreciated and thank you for all the work and effort in to this plugin.

**Pull request closed without merging**
